const LEVELS=[
 {id:'N5',jp:'初級',name:'Анхан шат',goal:'Хирагана, катакана, суурь ханз, өдөр тутмын энгийн хэллэг.',focus:'Өгүүлбэрийн суурь бүтэц · です／ます · цаг, тоо · богино яриа',plan:'7 хоногт 5 өдөр × 20 минут. Эхлээд үсэг, дараа нь түгээмэл үг ба богино өгүүлбэр.'},
 {id:'N4',jp:'基礎',name:'Суурь мэдлэг',goal:'Танил сэдвээр өдөр тутмын харилцан яриа ойлгох.',focus:'Үйл үгийн хувирал · て形 · энгийн холбоос · богино эх',plan:'N5-ийн мэдлэгээ шалгаад, өдөрт 10–15 шинэ үг ба нэг дүрмийг жишээтэй сур.'},
 {id:'N3',jp:'中級',name:'Дунд шат',goal:'Өдөр тутмын япон хэлний гол санаа болон тодорхой хэмжээний эх ойлгох.',focus:'Ойролцоо дүрмийг ялгах · мэдээний богино эх · харилцан ярианы далд утга',plan:'Унших ба сонсохыг ээлжил. Шинэ үгийг өгүүлбэр дотор сурч, долоо хоног бүр цагтай сорил хий.'},
 {id:'N2',jp:'中上級',name:'Дунд ахисан',goal:'Өргөн хүрээний сэдвээрх нийтлэл, мэдээг ойлгох чадвараа ахиулах.',focus:'Бичгийн хэлний дүрэм · урт эхийн логик · хурдтай сонсгол',plan:'Албан ба өдөр тутмын хэлний ялгааг тэмдэглэ. Алдааны шалтгааныг ангилж, сул хэсэгт цаг өг.'},
 {id:'N1',jp:'上級',name:'Ахисан',goal:'Өргөн сэдвийн нарийн, хийсвэр агуулгыг ойлгох түвшинд бэлтгэх.',focus:'Нарийн үгийн өнгө · урт нийтлэл · яригчийн байр суурь, далд санаа',plan:'Жинхэнэ эх сурвалж уншиж сонс. Цагтай бүтэн жишиг шалгалт хийж, хэсэг бүрийн ахицыг хэмж.'}
];
const QUIZ=[
 {q:'「水（みず）」の意味は何ですか。',a:['Ус','Гал','Мод','Цаг'],ok:0,why:'水（みず） гэдэг нь ус гэсэн утгатай.'},
 {q:'「学校（がっこう）」はどこですか。',a:['Эмнэлэг','Сургууль','Дэлгүүр','Банк'],ok:1,why:'学校（がっこう） гэдэг нь сургууль.'},
 {q:'「きのう」 гэдэг нь аль утгатай вэ?',a:['Маргааш','Өнөөдөр','Өчигдөр','Өглөө'],ok:2,why:'きのう（昨日） гэдэг нь өчигдөр.'},
 {q:'「私は毎日日本語を勉強します。」 Юу хийдэг вэ?',a:['Өдөр бүр япон хэл сурдаг','Япон руу өдөр бүр явдаг','Өдөр бүр ажилладаг','Ном өдөр бүр уншдаг'],ok:0,why:'勉強します нь сурах, хичээллэх гэсэн утгатай.'},
 {q:'「これは私の本です。」 гэдгийн 私 (わたし) нь?',a:['Найз','Багш','Би','Ном'],ok:2,why:'私（わたし） нь би гэсэн утгатай.'}
];
const $=s=>document.querySelector(s);let level=localStorage.getItem('nihongo-level')||'N5',qi=0,answered=false,score=0;
function renderLevels(){ $('#levels').innerHTML=LEVELS.map(l=>`<button class="level-card ${level===l.id?'active':''}" data-level="${l.id}"><span class="lv">${l.id}</span><span class="lv-jp">${l.jp}</span><small>${l.name}</small></button>`).join(''); document.querySelectorAll('.level-card').forEach(b=>b.onclick=()=>{level=b.dataset.level;localStorage.setItem('nihongo-level',level);renderLevels()}); const l=LEVELS.find(x=>x.id===level);$('#level-detail').innerHTML=`<b>${l.id} · ${l.name}</b><span>${l.goal} <b>Төвлөрөх нь:</b> ${l.focus}</span>`;$('#q-level').textContent=`${level} · СУРГАЛТЫН ЖИШЭЭ`}
function drawQuestion(){const q=QUIZ[qi];answered=false;$('#q-count').textContent=`${qi+1} / ${QUIZ.length}`;$('#quiz-progress').style.width=`${qi/QUIZ.length*100}%`;$('#question').textContent=q.q;$('#feedback').textContent='';$('#next-question').disabled=true;$('#next-question').textContent=qi===QUIZ.length-1?'Дахин эхлэх ↻':'Дараагийн асуулт →';$('#answers').innerHTML=q.a.map((a,i)=>`<button class="answer" data-i="${i}">${String.fromCharCode(65+i)}　${a}</button>`).join('');document.querySelectorAll('.answer').forEach(b=>b.onclick=()=>{if(answered)return;answered=true;const i=Number(b.dataset.i),right=i===q.ok;if(right)score++;b.classList.add(right?'correct':'wrong');document.querySelectorAll('.answer')[q.ok].classList.add('correct');$('#feedback').textContent=(right?'Зөв. ':'Дахин хараарай. ')+q.why;$('#next-question').disabled=false})}
$('#next-question').onclick=()=>{if(qi===QUIZ.length-1){qi=0;score=0;drawQuestion();return}qi++;drawQuestion()};$('#plan-btn').onclick=()=>{const s=Number(localStorage.getItem('nihongo-streak')||0);localStorage.setItem('nihongo-streak',String(s+1));updateStreak();$('#practice').scrollIntoView({behavior:'smooth'})};$('#streak').onclick=()=>$('#plan').scrollIntoView({behavior:'smooth'});function updateStreak(){$('#streak-count').textContent=localStorage.getItem('nihongo-streak')||'0'}renderLevels();drawQuestion();updateStreak();
