/* Progressive web app installation: native prompt where available, clear iOS/browser steps otherwise. */
(function(){
  "use strict";
  var promptEvent=null;
  var installed=false;
  var TEXT={
    mn:{button:"Суулгах",installed:"Суулгасан",title:"Утсандаа суулгах",intro:"Nihongo-г үндсэн дэлгэцэд нэмээд хичээл, хадгалсан ахицаа нэг товшилтоор нээ. Суралцах мэдээлэл энэ төхөөрөмжийн browser-д хадгалагдана.",ios:"iPhone эсвэл iPad · Safari",iosText:"Safari-ийн доод талын Хуваалцах товчийг дарж, “Add to Home Screen” / “Үндсэн дэлгэцэд нэмэх”-ийг сонго.",android:"Android · Chrome",androidText:"Chrome-ийн ⋮ цэсийг нээгээд “Install app” эсвэл “Add to Home screen”-ийг сонго.",desktop:"Компьютерийн browser",desktopText:"Хаягийн мөрний суулгах дүрс эсвэл browser-ийн цэснээс “Install Nihongo” командыг сонго.",offline:"Холболттой үед аппын үндсэн материал cache-д хадгалагдаж, сүлжээгүй үед дахин нээх боломжтой. Эхний удаа материал ачаалагдсаны дараа offline горимыг туршаарай.",close:"Хаах",privacy:"Бүртгэл шаардахгүй. Суралцах ахиц энэ browser, энэ төхөөрөмж дээр локал хадгалагдана."},
    en:{button:"Install",installed:"Installed",title:"Add Nihongo to your phone",intro:"Add Nihongo to your home screen for one-tap study. Your learning progress stays in this browser on this device.",ios:"iPhone or iPad · Safari",iosText:"Tap Safari’s Share button, then choose “Add to Home Screen.”",android:"Android · Chrome",androidText:"Open Chrome’s ⋮ menu, then choose “Install app” or “Add to Home screen.”",desktop:"Desktop browser",desktopText:"Use the install icon in the address bar or choose “Install Nihongo” from your browser menu.",offline:"Core study materials are cached while online and can be reopened offline. For best results, open the lessons once before going offline.",close:"Close",privacy:"No account is required. Study progress is stored locally in this browser on this device."},
    ja:{button:"アプリ追加",installed:"追加済み",title:"スマートフォンに追加",intro:"Nihongoをホーム画面に追加すると、ワンタップで学習を始められます。学習の進捗はこの端末のブラウザーに保存されます。",ios:"iPhone・iPad · Safari",iosText:"Safariの共有ボタンをタップし、「ホーム画面に追加」を選択します。",android:"Android · Chrome",androidText:"Chromeの⋮メニューを開き、「アプリをインストール」または「ホーム画面に追加」を選択します。",desktop:"デスクトップブラウザー",desktopText:"アドレスバーのインストールアイコン、またはブラウザーメニューから「Nihongoをインストール」を選択します。",offline:"オンライン中に学習教材がキャッシュされ、オフラインでも再度開けます。オフラインになる前に教材を一度開いてください。",close:"閉じる",privacy:"アカウントは不要です。学習の進捗はこの端末のブラウザー内に保存されます。"}
  };
  function lang(){return typeof language!=="undefined"&&TEXT[language]?language:"mn"}
  function tr(key){return TEXT[lang()][key]||TEXT.mn[key]||key}
  function esc(value){return String(value==null?"":value).replace(/[&<>"']/g,function(char){return {"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]})}
  function standalone(){return !!(window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches)||navigator.standalone===true}
  function render(){var button=document.querySelector("#install-app-btn"),title=document.querySelector("#pwa-dialog-title"),host=document.querySelector("#pwa-dialog-content"),close=document.querySelector("#pwa-dialog-close");if(button){var label=installed||standalone()?tr("installed"):tr("button");var labelEl=button.querySelector("[data-t]");if(labelEl)labelEl.textContent=label;button.setAttribute("aria-label",label);button.classList.toggle("is-installed",installed||standalone())}if(title)title.textContent=tr("title");if(close){close.setAttribute("aria-label",tr("close"));close.textContent="×"}if(host)host.innerHTML="<p class='pwa-intro'>"+esc(tr("intro"))+"</p><div class='pwa-platform-grid'><article><span></span><div><b>"+esc(tr("ios"))+"</b><p>"+esc(tr("iosText"))+"</p></div></article><article><span>◈</span><div><b>"+esc(tr("android"))+"</b><p>"+esc(tr("androidText"))+"</p></div></article><article><span>↗</span><div><b>"+esc(tr("desktop"))+"</b><p>"+esc(tr("desktopText"))+"</p></div></article></div><p class='pwa-offline-note'>◉ "+esc(tr("offline"))+"</p><p class='pwa-privacy-note'>"+esc(tr("privacy"))+"</p>"}
  function openGuide(){var dialog=document.querySelector("#pwa-install-dialog");if(!dialog)return;render();if(typeof dialog.showModal==="function"){if(!dialog.open)dialog.showModal()}else{dialog.setAttribute("open","");dialog.classList.add("is-open")}}
  function closeGuide(){var dialog=document.querySelector("#pwa-install-dialog");if(!dialog)return;if(typeof dialog.close==="function"&&dialog.open)dialog.close();else{dialog.removeAttribute("open");dialog.classList.remove("is-open")}}
  function requestInstall(){if(promptEvent){var saved=promptEvent;promptEvent=null;try{saved.prompt();Promise.resolve(saved.userChoice).then(function(result){if(result&&result.outcome==="accepted")installed=true;render()}).catch(function(){openGuide()})}catch{openGuide()}return}openGuide()}
  function setup(){var button=document.querySelector("#install-app-btn"),dialog=document.querySelector("#pwa-install-dialog"),close=document.querySelector("#pwa-dialog-close");if(button)button.onclick=requestInstall;if(close)close.onclick=closeGuide;if(dialog)dialog.addEventListener("click",function(event){if(event.target===dialog)closeGuide()});window.addEventListener("beforeinstallprompt",function(event){event.preventDefault();promptEvent=event;render()});window.addEventListener("appinstalled",function(){installed=true;promptEvent=null;render()});render()}
  window.NihongoPWA={refresh:render,openInstallGuide:openGuide};
  document.addEventListener("DOMContentLoaded",setup);
})();
