/* V8 Studio 3.0 — re-skins existing datasets without changing learning state. */
(function(){
'use strict';
var $=function(s){return document.querySelector(s)}, esc=function(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]})};
function status(type,id){try{return LearningStore.getStatus(LearningStore.getProgress(type,id))}catch{return'NEW'}}
function pct(type,id){try{var p=LearningStore.getProgress(type,id)||{};return Math.max(0,Math.min(100,Number(p.mastery||p.score||0)))}catch{return 0}}
function vocab(){var sec=$('#vocabulary'),data=LearningData.get('vocabulary');if(!sec||!data)return;sec.innerHTML="<div class='v8-studio'><div class='v8-studio-head'><div><div class='v8-eyebrow'>VOCABULARY STUDIO PRO</div><h2>Үгийн сан</h2><p>Уншлага, утга, жишээ болон бодит mastery-г нэг дор.</p></div><span class='v8-studio-meta'>"+data.length+" материал</span></div><div class='v8-studio-toolbar'><input id='v8-v-search' type='search' placeholder='Япон, уншлага, Монгол, English хайх…'><select id='v8-v-level'><option value='all'>Бүх түвшин</option>"+['N5','N4','N3','N2','N1'].map(function(x){return'<option>'+x+'</option>'}).join('')+"</select><select id='v8-v-status'><option value='all'>Бүх төлөв</option>"+['NEW','LEARNING','FAMILIAR','WEAK','MASTERED'].map(function(x){return'<option>'+x+'</option>'}).join('')+"</select></div><div id='v8-v-grid' class='v8-studio-grid'></div></div>";
var draw=function(){var q=$('#v8-v-search').value.toLowerCase(),lv=$('#v8-v-level').value,st=$('#v8-v-status').value,arr=data.filter(function(w){return(!q||[w.jp,w.reading,w.mn,w.en,w.example].some(function(v){return String(v||'').toLowerCase().includes(q)}))&&(lv==='all'||w.level===lv)&&(st==='all'||status('vocabulary',w.id)===st)}).slice(0,60);$('#v8-v-grid').innerHTML=arr.map(function(w){var s=status('vocabulary',w.id),p=pct('vocabulary',w.id);return"<article class='v8-studio-card'><div class='v8-studio-top'><span>"+esc(w.level||'—')+"</span><span>"+esc(s)+"</span></div><button type='button' data-id='"+esc(w.id)+"'><div><span class='v8-word' lang='ja'>"+esc(w.jp)+"</span><span class='v8-reading' lang='ja'>"+esc(w.reading||'')+"</span></div><div class='v8-meaning'>"+esc(w.mn||w.en||'')+"</div><div class='v8-example' lang='ja'>"+esc(w.example||'')+"</div></button><div class='v8-mini-progress'><i style='--pct:'+p+'%'></i></div></article>"}).join('')||"<div class='v8-empty'>Тохирох үг олдсонгүй.</div>";$('#v8-v-grid').querySelectorAll('[data-id]').forEach(function(b){b.onclick=function(){if(window.openVocabulary)window.openVocabulary(b.dataset.id);else if(window.markVocabularyViewed)window.markVocabularyViewed(b.dataset.id)}})};['input','change'].forEach(function(e){document.querySelectorAll('#v8-v-search,#v8-v-level,#v8-v-status').forEach(function(x){x.addEventListener(e,draw)})});draw()}
function kanji(){var sec=$('#kanji'),data=LearningData.get('kanji');if(!sec||!data)return;sec.innerHTML="<div class='v8-studio'><div class='v8-studio-head'><div><div class='v8-eyebrow'>KANJI STUDIO PRO</div><h2>漢字 · Ханз</h2><p>Бодит dataset дээр тулгуурласан ханзны progress.</p></div><span class='v8-studio-meta'>"+data.length+" материал</span></div><div class='v8-studio-grid' id='v8-k-grid'></div></div>";$('#v8-k-grid').innerHTML=data.slice(0,60).map(function(k){var s=status('kanji',k.id),p=pct('kanji',k.id);return"<article class='v8-studio-card'><div class='v8-studio-top'><span>"+esc(k.level||'—')+"</span><span>"+esc(s)+"</span></div><button type='button' data-id='"+esc(k.id)+"'><div class='v8-kanji' lang='ja'>"+esc(k.char)+"</div><div class='v8-meaning'>"+esc((k.related||[]).slice(0,3).map(function(x){return x.jp}).join(' · '))+"</div></button><div class='v8-mini-progress'><i style='--pct:'+p+'%'></i></div></article>"}).join('')||"<div class='v8-empty'>Ханзын dataset хоосон байна.</div>";$('#v8-k-grid').querySelectorAll('[data-id]').forEach(function(b){b.onclick=function(){if(window.openKanji)window.openKanji(b.dataset.id)}})}
function grammar(){var sec=$('#grammar'),data=LearningData.get('grammar');if(!sec||!data)return;sec.innerHTML="<div class='v8-studio'><div class='v8-studio-head'><div><div class='v8-eyebrow'>GRAMMAR STUDIO PRO</div><h2>文法 · Дүрэм</h2><p>Pattern-first бүтэц, жишээ болон mastery төлөв.</p></div><span class='v8-studio-meta'>"+data.length+" материал</span></div><div class='v8-studio-grid'>"+data.slice(0,60).map(function(g){var s=status('grammar',g.id),p=pct('grammar',g.id);return"<article class='v8-studio-card'><div class='v8-studio-top'><span>"+esc(g.level||'—')+"</span><span>"+esc(s)+"</span></div><button type='button' data-id='"+esc(g.id)+"'><div class='v8-grammar-pattern' lang='ja'>"+esc(g.pattern)+"</div><div class='v8-example' lang='ja'>"+esc(g.example||'')+"</div></button><div class='v8-mini-progress'><i style='--pct:'+p+'%'></i></div></article>"}).join('')+"</div></div>";sec.querySelectorAll('[data-id]').forEach(function(b){b.onclick=function(){if(window.openGrammar)window.openGrammar(b.dataset.id)}})}
function boot(){if(!window.LearningData||!window.LearningStore)return;vocab();kanji();grammar();window.addEventListener('hashchange',function(){setTimeout(function(){if(location.hash==='#vocabulary')vocab();if(location.hash==='#kanji')kanji();if(location.hash==='#grammar')grammar()},0)});if(window.Phase2UI){var old=window.Phase2UI.refresh;window.Phase2UI.refresh=function(){var x=old.apply(this,arguments);vocab();kanji();grammar();return x}}}
document.addEventListener('DOMContentLoaded',function(){setTimeout(boot,20)});
})();