import Link from "next/link";
import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { AppShell } from "@/components/app-shell";
import { hasSupabaseConfig } from "@/lib/supabase/config";
import { createClient } from "@/lib/supabase/server";
import SettingsForm from "@/components/settings-form";

const routes=["kanji","grammar","listening","reading","jlpt","progress","ai-tutor","settings"] as const;
const descriptions={
 mn:{kanji:["Ханз","Ханзны уншлага, утга, жишээ өгүүлбэрийг шалгасан эх өгөгдөл холбогдсоны дараа энд харуулна.","Хирагана давтах"],grammar:["Дүрэм","Жишээ болон орчуулгыг шалгасан дүрмийн сан холбогдсоны дараа энд сургалтын хичээлүүд гарна.","Үгийн сан үзэх"],listening:["Сонсгол","Сонсох материал одоогоор холбогдоогүй байна. Баталгаатай аудио болон тайлбарыг дараагийн үе шатанд оруулна.","Дасгалын сорил"],reading:["Уншлага","Унших дасгалын эх болон орчуулгыг өгөгдлийн сангаас татдаг болсны дараа энд гаргана.","Үгийн сан үзэх"],jlpt:["JLPT бэлтгэл","Одоогоор богино, өөрсдийн жишээ сорил бэлэн. Бүтэн хугацаатай жишиг шалгалт хараахан холбогдоогүй.","Богино сорил эхлүүлэх"],progress:["Миний ахиц","Зөвхөн бүртгэлтэй сургалтын session-ээс бодит хугацааг харуулна. Хичээл эхлүүлэхэд шинэ бүртгэл нэмэгдэнэ.","Суралцаж эхлэх"],"ai-tutor":["AI багш","AI багш Phase 3-т хамаарна. Энэ хувилбарт AI үйлчилгээ дуудагдахгүй, API түлхүүр ч клиентэд орохгүй.","Дасгал хийх"],settings:["Тохиргоо","Хэлний тохиргоог дээд хэсгээс сонгоно. Өдөр тутмын зорилго, түвшний сонголтыг хадгалах DB тохиргоо хараахан нэмэгдээгүй.","Нүүр самбар"]},
 en:{kanji:["Kanji","Kanji readings, meanings and examples will appear after reviewed source content is connected.","Review hiragana"],grammar:["Grammar","Reviewed grammar lessons will appear here when their source content is connected.","Open vocabulary"],listening:["Listening","Listening content is not connected yet. Reviewed audio and transcripts will be added in a later phase.","Practice quiz"],reading:["Reading","Reading passages and translations will appear after the content source is connected.","Open vocabulary"],jlpt:["JLPT preparation","A short original quiz is available. Full timed mock exams are not connected yet.","Start quick quiz"],progress:["My progress","Only recorded study sessions are shown. Start a study session to add a real record.","Start studying"],"ai-tutor":["AI tutor","The AI tutor belongs to Phase 3. This version does not call an AI service or expose an API key.","Practice quiz"],settings:["Settings","Choose your interface language in the header. Persistent goals and target levels are not configured in the database yet.","Dashboard"]},
 ja:{kanji:["漢字","確認済みの漢字・読み・意味・例文を連携後に表示します。","ひらがなを復習"],grammar:["文法","確認済みの文法教材を連携後に表示します。","単語を見る"],listening:["聴解","音声教材は未接続です。確認済みの音声と解説を後の段階で追加します。","練習テスト"],reading:["読解","読解教材と訳文は教材データ接続後に表示します。","単語を見る"],jlpt:["JLPT対策","独自の短い練習問題があります。時間制の模擬試験は未接続です。","ミニテスト"],progress:["学習の進捗","記録済みの学習時間のみ表示します。学習セッションを開始すると記録が追加されます。","学習を始める"],"ai-tutor":["AI先生","AI先生はPhase 3の機能です。この版ではAIを呼び出さず、APIキーも公開しません。","練習テスト"],settings:["設定","表示言語はヘッダーで切り替えられます。目標とレベルの保存機能はまだ設定されていません。","ホーム"]}
} as const;

export async function generateMetadata({params}:{params:Promise<{locale:string;section:string}>}):Promise<Metadata>{const{locale,section}=await params;if(!routes.includes(section as typeof routes[number]))return{};const text=descriptions[locale as keyof typeof descriptions]??descriptions.mn;return{title:text[section as keyof typeof text][0]}}

export default async function SectionPage({params}:{params:Promise<{locale:string;section:string}>}){
 const{locale,section}=await params;if(!routes.includes(section as typeof routes[number]))notFound();
 const copy=descriptions[locale as keyof typeof descriptions]??descriptions.mn;const [title,description,linkLabel]=copy[section as keyof typeof copy];
 let name=locale==="en"?"Learner":locale==="ja"?"学習者":"Суралцагч";let email="";let preferences={dailyGoal:20,target:"",learning:"daily"};
 if(hasSupabaseConfig()){const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(user){email=user.email||"";name=String(user.user_metadata.display_name||"").trim()||email.split("@")[0];if(section==="settings"){const{data}=await supabase.from("profiles").select("daily_goal_minutes,jlpt_target,learning_goal").eq("user_id",user.id).maybeSingle();if(data)preferences={dailyGoal:Number(data.daily_goal_minutes)||20,target:String(data.jlpt_target||""),learning:String(data.learning_goal||"daily")}}}}
 const destination=section==="kanji"||section==="grammar"||section==="reading"?`/${locale}/vocabulary`:section==="settings"?`/${locale}`:section==="progress"||section==="ai-tutor"?`/${locale}/study`:`/${locale}/quiz`;
 return <AppShell locale={locale} active={section} name={name} email={email}>{section==="settings"?<><section className="page-heading"><div><p className="eyebrow">{locale==="en"?"YOUR ACCOUNT":locale==="ja"?"アカウント":"ТАНЫ БҮРТГЭЛ"}</p><h1>{title}</h1><p>{description}</p></div></section><section className="settings-card"><div className="settings-profile"><span className="user-avatar">{name.trim().slice(0,1).toUpperCase()}</span><div><b>{name}</b><small>{email}</small></div></div><SettingsForm locale={locale} dailyGoal={preferences.dailyGoal} target={preferences.target} learning={preferences.learning}/><p className="settings-note">{locale==="en"?"Saving preferences requires the additive Supabase migration in this branch to be applied.":locale==="ja"?"設定を保存するには、このブランチの追加Supabaseマイグレーションを適用してください。":"Тохиргоо хадгалахын тулд энэ салбар дахь нэмэлт Supabase миграцийг ажиллуулах шаардлагатай."}</p></section></>:<section className="placeholder-panel"><span className="placeholder-glyph" aria-hidden="true">{section==="kanji"?"漢":section==="grammar"?"文":section==="listening"?"耳":section==="reading"?"読":section==="jlpt"?"試":section==="progress"?"↗":section==="ai-tutor"?"✳":"⚙"}</span><p className="eyebrow">{locale==="en"?"LEARNING SPACE":locale==="ja"?"学習スペース":"СУРАЛЦАХ ОРЧИН"}</p><h1>{title}</h1><p>{description}</p><Link className="button primary" href={destination}>{linkLabel} →</Link></section>}</AppShell>;
}
