import Link from "next/link";
import { AppShell } from "@/components/app-shell";

export type DashboardData = { minutesToday: number; dailyGoal: number; jlptTarget: string | null; weeklyMinutes: number[]; totalMinutes: number; streak: number; savedWords: number | null; error: boolean };

export default function Dashboard({ locale, name, email, data }: { locale: string; name: string; email: string; data: DashboardData }) {
  const copy = {
    mn: { hello:"Сайн уу", subtitle:"Өнөөдрийн сурах зорилго", goal:"Өдрийн зорилт", continue:"Хичээлээ эхлүүлэх", streak:"Өдөр дараалан", startAgain:"Өнөөдөр дахин эхэлье.", activities:"Өнөөдөр сурах нь", continueTitle:"Үргэлжлүүлэн сурах", first:"Анхны хичээлээ эхлүүлээрэй.", browse:"Хирагана давтах", vocab:"Үгийн сангаа нээх", quiz:"Богино сорил", progress:"Сүүлийн 7 хоног", total:"Нийт судалсан", minutes:"мин", empty:"Суралцаж эхлэхэд таны бодит ахиц энд харагдана.", saved:"Хадгалсан үг", savingUnavailable:"Өгөгдөл хараахан холбогдоогүй" },
    en: { hello:"Hello", subtitle:"Your learning day", goal:"Daily goal", continue:"Start studying", streak:"day streak", startAgain:"Today is a fresh start.", activities:"Recommended today", continueTitle:"Continue learning", first:"Start with your first lesson.", browse:"Review hiragana", vocab:"Open vocabulary", quiz:"Quick quiz", progress:"Last 7 days", total:"Total study time", minutes:"min", empty:"Your real progress will appear here as you study.", saved:"Saved words", savingUnavailable:"Data not connected yet" },
    ja: { hello:"こんにちは", subtitle:"今日の学習目標", goal:"一日の目標", continue:"学習を始める", streak:"日連続", startAgain:"今日からまた始めましょう。", activities:"今日のおすすめ", continueTitle:"学習を続ける", first:"最初のレッスンを始めましょう。", browse:"ひらがなを復習", vocab:"単語を見る", quiz:"ミニテスト", progress:"過去7日間", total:"学習時間", minutes:"分", empty:"学習を始めると、実際の進捗がここに表示されます。", saved:"保存した単語", savingUnavailable:"データ未接続" },
  }[locale as "mn"|"en"|"ja"] ?? { hello:"Сайн уу", subtitle:"Өнөөдрийн сурах зорилго", goal:"Өдрийн зорилт", continue:"Хичээлээ эхлүүлэх", streak:"Өдөр дараалан", startAgain:"Өнөөдөр дахин эхэлье.", activities:"Өнөөдөр сурах нь", continueTitle:"Үргэлжлүүлэн сурах", first:"Анхны хичээлээ эхлүүлээрэй.", browse:"Хирагана давтах", vocab:"Үгийн сангаа нээх", quiz:"Богино сорил", progress:"Сүүлийн 7 хоног", total:"Нийт судалсан", minutes:"мин", empty:"Суралцаж эхлэхэд таны бодит ахиц энд харагдана.", saved:"Хадгалсан үг", savingUnavailable:"Өгөгдөл хараахан холбогдоогүй" };
  const week = locale === "ja" ? ["月","火","水","木","金","土","日"] : locale === "en" ? ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"] : ["Да","Мя","Лх","Пү","Ба","Бя","Ня"];
  const percent = Math.min(100, Math.round((data.minutesToday / data.dailyGoal) * 100));
  const peak = Math.max(...data.weeklyMinutes, 1);
  return <AppShell locale={locale} active="home" name={name} email={email}>
    <section className="dash-welcome"><div><p className="eyebrow">{copy.subtitle}</p><h1>{copy.hello}, {name} <span>👋</span></h1><p>{locale === "ja" ? "自分のペースで一歩ずつ。" : locale === "en" ? "One focused step at a time." : "Өөрийн хурдаар, нэг нэг алхмаар."}</p></div><Link className="button primary" href={`/${locale}/study`}>{copy.continue} <span aria-hidden="true">→</span></Link></section>
    {data.error && <div className="inline-alert" role="status">{locale === "en" ? "We could not load your saved progress. Your account is safe; try again later." : locale === "ja" ? "学習記録を読み込めませんでした。後でもう一度お試しください。" : "Ахицын мэдээлэл ачаалж чадсангүй. Бүртгэл хэвээр; дараа дахин оролдоно уу."}</div>}
    <section className="dash-top-grid"><article className="goal-card"><div className="card-title-row"><div><p className="eyebrow">{copy.goal}</p><strong>{data.dailyGoal} <small>{copy.minutes}</small></strong></div><span className="goal-ring" style={{"--progress":`${percent}%`} as import("react").CSSProperties}><b>{percent}%</b></span></div><div className="progress-track"><i style={{width:`${percent}%`}}/></div><p className="goal-caption">{data.minutesToday} / {data.dailyGoal} {copy.minutes} <span>· {locale === "en" ? "daily preference" : locale === "ja" ? "設定した目標" : "таны өдөр тутмын зорилт"}</span></p>{data.jlptTarget&&<span className="target-badge">{locale==="ja"?"目標":"Зорилго"} · {data.jlptTarget}</span>}</article><article className="streak-card"><div className="streak-symbol">火</div><p className="eyebrow">{locale === "ja" ? "継続記録" : locale === "en" ? "CONSISTENCY" : "ТУУШТАЙ БАЙДАЛ"}</p><strong>{data.streak} <small>{copy.streak}</small></strong><p>{data.streak > 0 ? (locale === "ja" ? "いいペースです。続けましょう。" : locale === "en" ? "A good rhythm. Keep going." : "Сайн хэмнэл байна. Үргэлжлүүлээрэй.") : copy.startAgain}</p></article></section>
    <section className="dash-columns"><div className="dash-column-main"><div className="dash-section-head"><div><p className="eyebrow">{copy.activities}</p><h2>{locale === "en" ? "A useful next step" : locale === "ja" ? "次の一歩" : "Дараагийн хэрэгтэй алхам"}</h2></div><span className="live-label"><i/> {locale === "en" ? "READY" : locale === "ja" ? "学習可能" : "БЭЛЭН"}</span></div><div className="activity-list"><Link href={`/${locale}/kana`}><span className="activity-glyph">あ</span><span><b>{copy.browse}</b><small>46 {locale === "en" ? "basic characters" : locale === "ja" ? "基本文字" : "үндсэн тэмдэгт"}</small></span><span className="activity-arrow">↗</span></Link><Link href={`/${locale}/vocabulary`}><span className="activity-glyph">語</span><span><b>{copy.vocab}</b><small>24 {locale === "en" ? "reviewed starter words" : locale === "ja" ? "確認済みの基本単語" : "хянасан эхний үг"}</small></span><span className="activity-arrow">↗</span></Link><Link href={`/${locale}/quiz`}><span className="activity-glyph">問</span><span><b>{copy.quiz}</b><small>5 {locale === "en" ? "original questions" : locale === "ja" ? "オリジナル問題" : "өөрсдийн жишээ асуулт"}</small></span><span className="activity-arrow">↗</span></Link></div><article className="continue-card"><div><p className="eyebrow">{copy.continueTitle}</p><h3>{locale === "ja" ? "学習履歴" : locale === "en" ? "Your study history" : "Таны суралцсан түүх"}</h3><p>{data.totalMinutes ? `${data.totalMinutes} ${copy.minutes}` : copy.first}</p></div><Link href={`/${locale}/study`} aria-label={copy.continue}>→</Link></article></div>
    <aside className="dash-side"><div className="dash-section-head"><div><p className="eyebrow">{copy.progress}</p><h2>{locale === "en" ? "Study time" : locale === "ja" ? "学習時間" : "Суралцсан хугацаа"}</h2></div><span className="chart-total">{data.weeklyMinutes.reduce((a,b)=>a+b,0)} <small>{copy.minutes}</small></span></div><div className="week-chart" role="img" aria-label={`${copy.progress}: ${data.weeklyMinutes.join(", ")} ${copy.minutes}`}><div className="chart-bars">{data.weeklyMinutes.map((m,i)=><div className="chart-day" key={week[i]}><span className="bar-value">{m || ""}</span><span className="bar-track"><i style={{height:`${m ? Math.max(6,Math.round((m/peak)*100)) : 0}%`}}/></span><small>{week[i]}</small></div>)}</div><p className="chart-caption">{data.weeklyMinutes.some(Boolean) ? (locale === "en" ? "Minutes recorded from your study sessions" : locale === "ja" ? "学習記録に基づく分数" : "Сургалтын бүртгэлээс тооцсон минут") : copy.empty}</p></div><div className="mini-metric"><span>{copy.saved}</span><b>{data.savedWords === null ? "—" : data.savedWords}</b></div></aside></section>
  </AppShell>;
}
