"use client";

import { useMemo, useState } from "react";
import { starterQuiz, type StarterQuestion } from "@/lib/starter-content";

function shuffle<T>(items:T[]):T[]{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result}
type QuizItem={question:StarterQuestion;answers:string[];correct:number};

export default function QuickQuiz({locale}:{locale:string}){
  const [started,setStarted]=useState(false);const [items,setItems]=useState<QuizItem[]>([]);const [index,setIndex]=useState(0);const [choice,setChoice]=useState<number|null>(null);const [score,setScore]=useState(0);
  const labels=locale==="en"?{title:"Quick vocabulary check",intro:"Five original practice questions. Answer order changes each time.",start:"Start quiz",next:"Next question",finish:"See result",restart:"Try again",question:"QUESTION",result:"Your result",correct:"Correct",incorrect:"Review this one",explanation:"Explanation",empty:"These are original study questions, not official JLPT items."}:locale==="ja"?{title:"単語のミニテスト",intro:"オリジナルの練習問題5問です。出題と選択肢の順番は毎回変わります。",start:"テストを始める",next:"次の問題",finish:"結果を見る",restart:"もう一度",question:"問題",result:"結果",correct:"正解",incorrect:"復習しましょう",explanation:"解説",empty:"独自の練習問題です。JLPT公式問題ではありません。"}:{title:"Богино үгийн сорил",intro:"Өөрсдийн бэлтгэсэн 5 асуулт. Асуулт, сонголтын дараалал бүр эхлэхэд холигдоно.",start:"Тест эхлүүлэх",next:"Дараагийн асуулт",finish:"Үр дүн харах",restart:"Дахин эхлэх",question:"АСУУЛТ",result:"Таны үр дүн",correct:"Зөв",incorrect:"Дахин давтаарай",explanation:"Тайлбар",empty:"Эдгээр нь сургалтын зориулалтаар бэлтгэсэн жишээ. Албан ёсны JLPT асуулт биш."};
  const words=useMemo(()=>locale==="en"?"words":locale==="ja"?"問":"асуулт",[locale]);
  function begin(){const localeKey=locale==="en"?"en":locale==="ja"?"ja":"mn";const shuffled=shuffle([...starterQuiz]).map((question)=>{const answers=shuffle([...question.a[localeKey]]);return{question,answers,correct:answers.indexOf(question.a[localeKey][question.ok])}});setItems(shuffled);setIndex(0);setScore(0);setChoice(null);setStarted(true)}
  if(!started)return <section className="quiz-panel"><div className="quiz-intro-mark">問</div><h2>{labels.title}</h2><p>{labels.intro}</p><span className="quiz-count-badge">{starterQuiz.length} {words}</span><button className="button primary" type="button" onClick={begin}>{labels.start} →</button><small>{labels.empty}</small></section>;
  if(index>=items.length)return <section className="quiz-panel quiz-result"><div className="quiz-intro-mark">✓</div><p className="eyebrow">{labels.result}</p><h2>{score} / {items.length}</h2><p>{labels.empty}</p><button className="button primary" type="button" onClick={begin}>{labels.restart}</button></section>;
  const item=items[index];const localeKey=locale==="en"?"en":locale==="ja"?"ja":"mn";
  return <section className="quiz-panel"><div className="quiz-heading"><span>{labels.question} {index+1} / {items.length}</span><span>{score} ✓</span></div><div className="quiz-track"><i style={{width:`${Math.round(index/items.length*100)}%`}}/></div><h2 lang="ja">{localeKey==="mn"?item.question.q:localeKey==="en"?item.question.en:item.question.ja}</h2><div className="quiz-options" role="group" aria-label={labels.question}>{item.answers.map((answer,i)=><button type="button" key={`${i}-${answer}`} disabled={choice!==null} aria-pressed={choice===i} onClick={()=>{setChoice(i);if(i===item.correct)setScore((old)=>old+1)}} className={`quiz-option ${choice!==null&&i===item.correct?"answer-correct":""} ${choice===i&&i!==item.correct?"answer-wrong":""}`}><span>{String.fromCharCode(65+i)}</span>{answer}</button>)}</div>{choice!==null&&<div className={`quiz-feedback ${choice===item.correct?"is-correct":"is-wrong"}`} role="status"><b>{choice===item.correct?labels.correct:labels.incorrect}</b><p>{labels.explanation}: {item.question.why[localeKey]}</p></div>}<button className="button primary quiz-next" type="button" disabled={choice===null} onClick={()=>{setIndex((old)=>old+1);setChoice(null)}}>{index===items.length-1?labels.finish:labels.next} →</button><small>{labels.empty}</small></section>;
}
