import Link from "next/link";

const content = {
  mn: {
    privacy: { title: "Нууцлалын бодлого", intro: "Nihongo таны мэдээллийг сургалтын бүртгэл үүсгэх, үйлчилгээг ажиллуулахад ашиглана.", sections: [["Цуглуулах мэдээлэл", "Бүртгүүлэх үед имэйл хаяг, таны оруулсан нэр, интерфэйсийн хэл хадгалагдана. Сургалтын ахиц синк хийх боломжийг нэвтрүүлэх үед холбогдох сургалтын мэдээлэл таны бүртгэлтэй холбоно."], ["Хадгалалт ба хамгаалалт", "Бүртгэлийн мэдээлэл Supabase-ийн хамгаалалттай үйлчилгээнд хадгалагдана. Нууц үгийг Nihongo текстээр хадгалдаггүй; баталгаажуулалтыг үйлчилгээ үзүүлэгч хариуцна."], ["Хуваалцах ба хяналт", "Бид мэдээллийг худалдахгүй. Бүртгэлээ устгуулах эсвэл мэдээллийн талаар хүсэлт гаргахдаа үйлчилгээний эзэмшигчтэй холбоо барина уу. Холбоо барих хаяг нийтэд зарлагдаагүй байгаа тул энэ хуудсыг нийтлэхийн өмнө бодит холбоо барих мэдээллээр шинэчилнэ үү."], ["Одоогийн хүрээ", "Энэ хувилбарт төлбөр, сурталчилгааны мөрдөлт, аналитик хэрэгжээгүй. Нууцлалын бодлого нь үйлчилгээ бүрэн нээгдэхээс өмнө эцсийн хяналт шаардсан эх загвар юм."]] },
    terms: { title: "Үйлчилгээний нөхцөл", intro: "Nihongo нь япон хэл сурахад зориулсан бие даан боловсруулж буй сургалтын платформ юм.", sections: [["Сургалтын материал", "Материалууд нь дадлага, суралцахад зориулагдсан бөгөөд JLPT-ийн албан ёсны шалгалт, баталгаатай оноо, эсвэл бүрэн хөтөлбөрийг орлохгүй."], ["Бүртгэл", "Та бүртгэлийн мэдээллээ үнэн зөв байлгаж, нууц үгээ хамгаална. Өөр хүний бүртгэлд зөвшөөрөлгүй нэвтрэх, үйлчилгээг саатуулах, хууль бус зорилгоор ашиглахыг хориглоно."], ["Үйлчилгээний төлөв", "Үйлчилгээ болон сургалтын агуулга өөрчлөгдөж болно. Төлбөртэй багц одоогоор санал болгоогүй; төлбөрийн эрх эсвэл захиалгын төлөвийг энэ хувилбарт үүсгэдэггүй."], ["Нөхцөлийн төлөв", "Энэ бол нээлтийн өмнөх эх загвар бөгөөд үйлчилгээ нийтэд нээгдэхээс өмнө эзэмшигч, хүчин төгөлдөр огноо, холбоо барих мэдээллийг нэмж хуулийн хяналтаар баталгаажуулна."]] },
  },
  en: {
    privacy: { title: "Privacy policy", intro: "Nihongo uses your information to provide account and learning services.", sections: [["Information collected", "When you register, we store your email address, the name you provide, and interface language. Learning activity may be associated with your account when progress sync is available."], ["Storage and security", "Account data is stored with Supabase. Nihongo does not store your password as readable text; authentication is handled by the identity provider."], ["Sharing and requests", "We do not sell personal data. Contact the service operator to request account deletion or ask about your data. A public contact address has not yet been supplied and must be added before publication."], ["Current scope", "Payments, advertising trackers, and analytics are not implemented in this version. This draft needs final review before public launch."]] },
    terms: { title: "Terms of service", intro: "Nihongo is an independently developed platform for Japanese language study.", sections: [["Learning material", "Content is provided for practice and study. It is not an official JLPT exam, a score guarantee, or a complete syllabus."], ["Account", "Keep your account information accurate and protect your password. Do not access another person's account without permission, disrupt the service, or use it unlawfully."], ["Service status", "Features and learning content may change. No paid plan is currently offered, and this version does not create payment entitlements or subscriptions."], ["Draft status", "This is a pre-launch draft. The operator, effective date, contact details, and legal review must be completed before public launch."]] },
  },
  ja: {
    privacy: { title: "プライバシーポリシー", intro: "Nihongoはアカウントと学習サービスの提供に必要な情報を利用します。", sections: [["取得する情報", "登録時にメールアドレス、入力された名前、表示言語を保存します。学習記録の同期機能が利用可能な場合、学習情報をアカウントに関連付けます。"], ["保存と保護", "アカウント情報はSupabaseに保存します。パスワードを平文では保存せず、認証は認証サービスが処理します。"], ["共有とお問い合わせ", "個人情報を販売しません。アカウント削除や情報開示の依頼は運営者にご連絡ください。公開連絡先は未設定のため、公開前に追加が必要です。"], ["現在の範囲", "この版では決済、広告トラッカー、分析機能は実装していません。公開前に最終確認が必要な草案です。"]] },
    terms: { title: "利用規約", intro: "Nihongoは日本語学習のために独自に開発しているプラットフォームです。", sections: [["学習教材", "教材は学習と練習を目的とし、JLPT公式試験、スコア保証、完全なシラバスの代替ではありません。"], ["アカウント", "登録情報を正確に保ち、パスワードを管理してください。無断アクセス、サービス妨害、違法な利用は禁止します。"], ["サービス状況", "機能や教材は変更される場合があります。現在、有料プランはなく、この版では支払い権限や契約を発行しません。"], ["草案について", "公開前の草案です。運営者、施行日、連絡先を追加し、法的確認を終えてから公開してください。"]] },
  },
} as const;

export default function LegalPage({ locale, kind }: { locale: string; kind: "privacy" | "terms" }) {
  const language = content[locale as keyof typeof content] ?? content.mn;
  const page = language[kind];
  return <main className="shell learning-shell legal-shell"><header className="topbar"><Link className="brand" href={`/${locale}`}><span className="brand-mark">日</span>nihongo<span className="brand-dot">.</span></Link><Link className="back-link" href={`/${locale}`}>{locale === "ja" ? "← ホーム" : locale === "en" ? "← Home" : "← Нүүр хуудас"}</Link></header><article className="legal-content"><p className="eyebrow">NIHONGO · {kind === "privacy" ? "PRIVACY" : "TERMS"}</p><h1>{page.title}</h1><p className="legal-intro">{page.intro}</p>{page.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}</article><footer>© Nihongo · {locale === "ja" ? "独自の学習教材" : locale === "en" ? "Independent learning material" : "Бие даасан сургалтын материал"}</footer></main>;
}
